Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
